## Assignment 1 – Julia Widén
Python Programming for Business Intelligence

### Task 1

In [1]:
transactions = [
    {"id": 1, "product": "Laptop", "price": 1200, "quantity": 2, "region": "EU"},
    {"id": 2, "product": "Phone", "price": 800, "quantity": -1, "region": "US"},
    {"id": 3, "product": "Tablet", "price": 0, "quantity": 5, "region": "EU"},
    {"id": 4, "product": "Monitor", "price": 350, "quantity": 3, "region": "US"},
    {"id": 5, "product": "Laptop", "price": 1200, "quantity": 1, "region": "EU"},
    {"id": 6, "product": "Keyboard", "price": 75, "quantity": 10, "region": "APAC"},
]

# a) 
filtered_transactions = [item for item in transactions if item['price'] > 0 and item['quantity'] >= 0]

# b)
for item in filtered_transactions:
    item['total'] = item['price'] * item['quantity']
    
# c) Grouping and computing revenue by region, storing in a dictionary
revenue_per_region = {}
for item in filtered_transactions:
    if item['region'] in revenue_per_region:
        revenue_per_region[item['region']] = revenue_per_region[item['region']] + item['total']
    else:
        revenue_per_region[item['region']] = item['total']
        
# d) Printing the region with the highest total revenue and its value using an f-string
highest_region = max(revenue_per_region, key=revenue_per_region.get)
highest_value = revenue_per_region[highest_region]

answer = f"{highest_region} has the highest total revenue at {highest_value}!"
print(answer)

EU has the highest total revenue at 3600!

### Task 2

In [2]:
sales = [1200, 980, 1540, 870, 2010, 1650, 1300, 1100, 950, 1780, 2200, 1430, 1600, 1900]

def summarise_sales(sales): # defining the function
    total = sum(sales) # calculating the total sum of sales during the past 2 weeks
    average = round(sum(sales) / len(sales), 2) # finding the average and rounding to two decimals
    best_day = sales.index(max(sales)) + 1 # finding the day with the highest sales starting from the first day
    worst_day = sales.index(min(sales)) + 1 # finding the day with the lowest sales starting from the first day
    above_average_count = len([item for item in sales if item > average]) # finding the days where the sales exceeded the average
    
    return { 
        "total": total,
        "average": average,
        "best_day": best_day,
        "worst_day": worst_day,
        "above_average_count": above_average_count
    } 
print(summarise_sales(sales))

{'total': 20510, 'average': 1465.0, 'best_day': 11, 'worst_day': 4, 'above_average_count': 7}

### Task 3

In [3]:
students = [
    {"name": "Anna", "grade": 85, "attendance": 0.92},
    {"name": "Erik", "grade": 58, "attendance": 0.75},
    {"name": "Mia", "grade": 91, "attendance": 0.98},
    {"name": "Leo", "grade": 44, "attendance": 0.60},
    {"name": "Sara", "grade": 72, "attendance": 0.88},
    {"name": "Tom", "grade": 67, "attendance": 0.70},
    {"name": "Nina", "grade": 95, "attendance": 0.99},
    {"name": "Olli", "grade": 50, "attendance": 0.65},
]

In [4]:
# a) Creating a list of students who have a passing grade (50 or above)
passing = [item['name'] for item in students if item['grade'] >= 50]
print(passing)

['Anna', 'Erik', 'Mia', 'Sara', 'Tom', 'Nina', 'Olli']

In [5]:
# b) Looping through students and print their status based on their grade
for item in students:
    if item['grade'] >= 80:
        result = "Excellent"
    elif item['grade'] >= 50:
        result = "Pass"
    else:
        result = "Fail"
   
    print(f" {item['name']}: {result}")

 Anna: Excellent
 Erik: Pass
 Mia: Excellent
 Leo: Fail
 Sara: Pass
 Tom: Pass
 Nina: Excellent
 Olli: Pass

In [6]:
# c) Counting how many students have an attendance rate below 0.80
count = len([item for item in students if item['attendance'] < 0.80])
print(count)

4

In [7]:
# d) Finding the student with the highest grade using a for loop
best_student = students[0] 

for item in students:
    if item['grade'] > best_student['grade']:
        best_student = item 
print(f"{best_student['name']} {best_student['grade']}")

Nina 95

In [8]:
# e) Finding the student with the highest grade using max()
def what_grade(s):
    return s['grade']

best_student_max = max(students, key=what_grade)

print(f"{best_student_max['name']} {best_student_max['grade']}")

Nina 95

### Task 4

In [9]:
class Portfolio:
    def __init__(self, owner):
        self.owner = owner
        self.holdings = {}
        
    # a)
    def add_asset(self, ticker, shares, price_per_share):
        self.holdings[ticker] = {"shares": shares, "price_per_share": price_per_share}
    
    # b)
    def total_value(self):
        total = 0
        for ticker in self.holdings:
            total = total + self.holdings[ticker]['shares'] * self.holdings[ticker]['price_per_share']
        return total

    # c) 
    def most_valuable(self):
        return max(self.holdings, key=lambda ticker: self.holdings[ticker]['shares'] * self.holdings[ticker]['price_per_share'])
    
    # d) 
    def __str__(self):
        return f"Owner: {self.owner}, Assets: {len(self.holdings)}, Total Value: {self.total_value()}"
    
# Putting it all together

my_portfolio = Portfolio("Julia") # Creating an instance

my_portfolio.add_asset("NVDA", 10, 167.5) # Adding 3 assets
my_portfolio.add_asset("AAPL", 5, 248.8)
my_portfolio.add_asset("MSFT", 3, 356.8)

print(my_portfolio.total_value()) # Demonstrating the methods
print(my_portfolio.most_valuable())
print(my_portfolio)

3989.4
NVDA
Owner: Julia, Assets: 3, Total Value: 3989.4

### Task 5

In [10]:
import datetime # Importing the datetime module

orders = [
    ("2025-01-15", "Laptop"), ("2025-01-22", "Phone"),
    ("2025-02-03", "Laptop"), ("2025-02-14", "Tablet"),
    ("2025-03-01", "Phone"), ("2025-03-10", "Phone"),
    ("2025-03-22", "Laptop"), ("2025-04-05", "Monitor"),
]

dates = [datetime.datetime.strptime(order[0], "%Y-%m-%d").date() for order in orders]

earliest_order = min(dates) 
latest_order = max(dates)

# computing the number of days between the latest and earliest order using the difference of the two
difference = latest_order - earliest_order
print(difference.days)

80

### Task 6

In [11]:
import numpy as np

# Rows: years (2022, 2023, 2024), Columns: quarters (Q1, Q2, Q3, Q4)
revenue = np.array([
    [210, 230, 190, 250],
    [220, 260, 200, 270],
    [250, 290, 230, 310]])

In [12]:
# a) 
print(revenue.sum(axis=1))

[ 880  950 1080]

In [13]:
# b) 
print(revenue.mean(axis=0))

[226.66666667 260.         206.66666667 276.66666667]

In [14]:
# c)
growth = np.array([1.05, 1.03, 1.08, 1.02])
print(revenue[2] * growth) # 2024 is the third row but I'm using [2] because python starts counting from 0

[262.5 298.7 248.4 316.2]

In [15]:
# d) single line booleon indexing to find quarterly revenue values that exceed 250 (thousands of euros)
print(revenue[revenue > 250])

[260 270 290 310]

### Task 7

In [16]:
import pandas as pd

data = {
    "employee": ["Anna", "Erik", "Mia", "Leo", "Sara", "Tom"],
    "department": ["Finance", "Marketing", "Finance", "IT", "Marketing", "IT"],
    "salary": [4500, 4000, 4800, 5200, 3900, 5100],
    "years_exp": [5, 3, 7, 10, 2, 8],
    "performance_score": [4.2, 3.8, 4.5, 4.0, 3.5, 4.9]
}

HR_data = pd.DataFrame(data)
HR_data

  employee department  salary  years_exp  performance_score
0     Anna    Finance    4500          5                4.2
1     Erik  Marketing    4000          3                3.8
2      Mia    Finance    4800          7                4.5
3      Leo         IT    5200         10                4.0
4     Sara  Marketing    3900          2                3.5
5      Tom         IT    5100          8                4.9

In [17]:
# a) add salary_per_year_exp column
HR_data["salary_per_year_exp"] = (HR_data["salary"] / HR_data["years_exp"]).round(0)

# b) ascending=false gives the highest score first, .head(3) gives us the 3 top employees
HR_data.sort_values("performance_score", ascending=False).head(3)

,employee,department,salary,years_exp,performance_score,salary_per_year_exp
5,Tom,IT,5100,8,4.9,638.0
2,Mia,Finance,4800,7,4.5,686.0
0,Anna,Finance,4500,5,4.2,900.0

In [18]:
# c) 
HR_data.loc[(HR_data["department"] == "Finance") & (HR_data["performance_score"] > 4.0)]

,employee,department,salary,years_exp,performance_score,salary_per_year_exp
0,Anna,Finance,4500,5,4.2,900.0
2,Mia,Finance,4800,7,4.5,686.0

In [19]:
# d)
HR_data = HR_data.rename(columns={"years_exp": "experience_years"})
HR_data

,employee,department,salary,experience_years,performance_score,salary_per_year_exp
0,Anna,Finance,4500,5,4.2,900.0
1,Erik,Marketing,4000,3,3.8,1333.0
2,Mia,Finance,4800,7,4.5,686.0
3,Leo,IT,5200,10,4.0,520.0
4,Sara,Marketing,3900,2,3.5,1950.0
5,Tom,IT,5100,8,4.9,638.0

In [20]:
# e) rows 0-4 and columns 2 (salary) and 4 (performance score)
HR_data.iloc[0:4, [2,4]]

   salary  performance_score
0    4500                4.2
1    4000                3.8
2    4800                4.5
3    5200                4.0

### Task 8

In [21]:
import numpy as np
import pandas as pd

rng = np.random.default_rng(seed=123)
days = pd.date_range(start="2025-01-06", periods=28, freq="D")
visitors = rng.integers(200, 600, size=28)
conversion_rate = rng.uniform(0.02, 0.08, size=28).round(4)
avg_order_value = rng.normal(50, 10, size=28).round(2)

In [22]:
# a) Creating DataFrame
traffic_data = pd.DataFrame({ 
    "date": days,
    "visitors": visitors,
    "conversion_rate": conversion_rate,
    "avg_order_value": avg_order_value
})

traffic_data = traffic_data.set_index("date") # Setting date as index

In [23]:
# b) 
traffic_data["conversions"] = (traffic_data["visitors"] * traffic_data["conversion_rate"]).round(0) # New column 1
traffic_data["daily_revenue"] = traffic_data["conversions"] * traffic_data["avg_order_value"] # New column 2

# Printing to check for accuracy
traffic_data

,visitors,conversion_rate,avg_order_value,conversions,daily_revenue
date,,,,,
2025-01-06,206,0.0645,64.30,13.0,835.90
2025-01-07,472,0.0578,48.44,27.0,1307.88
2025-01-08,437,0.0756,43.26,33.0,1427.58
2025-01-09,221,0.0339,43.61,7.0,305.27
2025-01-10,563,0.0679,49.39,38.0,1876.82
2025-01-11,288,0.0511,46.07,15.0,691.05
2025-01-12,302,0.0339,72.90,10.0,729.00
2025-01-13,273,0.0300,42.82,8.0,342.56
2025-01-14,333,0.0499,50.33,17.0,855.61
2025-01-15,270,0.0550,50.28,15.0,754.20
2025-01-16,339,0.0311,50.28,11.0,553.08
2025-01-17,524,0.0209,50.55,11.0,556.05
2025-01-18,380,0.0483,45.18,18.0,813.24
2025-01-19,569,0.0637,44.17,36.0,1590.12
2025-01-20,379,0.0751,41.38,28.0,1158.64
2025-01-21,310,0.0575,35.12,18.0,632.16
2025-01-22,515,0.0750,52.16,39.0,2034.24
2025-01-23,527,0.0719,59.84,38.0,2273.92
2025-01-24,544,0.0331,44.57,18.0,802.26
2025-01-25,555,0.0720,44.41,40.0,1776.40
2025-01-26,210,0.0638,46.84,13.0,608.92
2025-01-27,405,0.0367,45.39,15.0,680.85
2025-01-28,307,0.0678,35.64,21.0,748.44
2025-01-29,297,0.0719,63.65,21.0,1336.65
2025-01-30,296,0.0380,54.39,11.0,598.29
2025-01-31,529,0.0516,42.88,27.0,1157.76
2025-02-01,516,0.0243,52.97,13.0,688.61
2025-02-02,285,0.0550,45.62,16.0,729.92